### ISSUE TITLE
Linux support

### ISSUE THREAD

**Issue by tmcw** [openlawdc/dc-decoded#1]
Right now converting `.doc` to `.html` uses `textutil`, which is mac-only. It's possible to do the same with `soffice` and rely on [LibreOffice](http://www.libreoffice.org/) instead, but I've had no luck getting this running.

**Comment by waldoj** [comment]
FWIW, I've never found anything even vaguely as good as `textutil` for the DOC->HTML conversion. It's been a couple of years since I've investigated this seriously, admittedly.

**Comment by konklone** [comment]
This [SO answer](http://unix.stackexchange.com/questions/20859/is-there-a-linux-equivalent-of-the-mac-os-x-command-textutil) mentions three options:
- [Pandoc](http://johnmacfarlane.net/pandoc/), looks promising, doesn't appear to require OO/LO
- [UnRTF](http://www.gnu.org/software/unrtf/) but that only handles RTF as input
- [unoconv](http://dag.wieers.com/home-made/unoconv/) is an interface to OpenOffice (and presumably LibreOffice)

**Comment by konklone** [comment]
Nuts - Pandoc converts _to_ docx and ODT, doesn't accept them as input (or normal .doc files). So maybe `soffice` or `unoconv`.

**Comment by tmcw** [comment]
y, so unfortunately Pandoc doesn't deal with doc as an input format.

originally I was thinking that Word formatting would actually be useful here - doesn't look like it is, so [catdoc](http://www.wagner.pp.ru/~vitus/software/catdoc/) might fit the bill for cross-platform.
