### ISSUE TITLE
Certain pages appear overwritten in 47-2853

### ISSUE THREAD

**Issue by myersjustinc** [openlawdc/dc-decoded#23]
(Maybe in other places, too, but this is at least where I saw it.)

47-2853.133 is showing up under 47-2853.13: http://dccode.org/browser/#/47/47-2853.13 http://dccode.org/simple/sections/47-2853.13.html

**Comment by JoshData** [comment]
Hi, Justin. Thanks.

It appears OK in our newer openlawdc/simple-2 browser which is based on newer base data:
http://dccode.org/dccode/Title-47/Chapter-28/Subchapter-I-B/Part-J/47-2853.133.html

We will probably retire or update dccode.org/browser and dccode.org/simple soon.

Thanks for spotting the issue!
